-- =============================================================================
-- 0019 · Engagement domain — tables
-- docs/03-database-design.md §8, §13.2
-- =============================================================================
--
-- Prisma-generated DDL, with the usual DropIndex/DropForeignKey/color_lab/
-- available_m2/RenameIndex diff noise excluded (see prior domain migrations
-- for why). product_view is built directly as a monthly RANGE-partitioned
-- table (by viewed_at, per §13.2) rather than created plain and converted
-- afterward — it's new, so there's no data-safety reason to do it in two
-- steps the way inventory_movement's retrofit needed.

-- CreateEnum
CREATE TYPE "product_view_source" AS ENUM ('catalog', 'search', 'finder', 'assistant', 'related', 'direct', 'collection');

-- CreateEnum
CREATE TYPE "project_status" AS ENUM ('draft', 'active', 'presented', 'approved', 'completed', 'archived');

-- CreateEnum
CREATE TYPE "project_item_role" AS ENUM ('floor', 'wall', 'splashback', 'trim', 'feature', 'alternative');

-- CreateEnum
CREATE TYPE "project_share_permission" AS ENUM ('view', 'comment');

-- CreateEnum
CREATE TYPE "stock_alert_channel" AS ENUM ('email', 'whatsapp', 'both');

-- CreateEnum
CREATE TYPE "stock_alert_status" AS ENUM ('active', 'notified', 'expired', 'cancelled');

-- CreateTable
CREATE TABLE "saved_item" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "visitor_id" UUID NOT NULL,
    "app_user_id" UUID,
    "product_id" UUID NOT NULL,
    "project_id" UUID,
    "note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "saved_item_pkey" PRIMARY KEY ("id")
);

-- CreateTable (partitioned — see file header)
CREATE TABLE "product_view" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" UUID NOT NULL,
    "visitor_id" UUID,
    "app_user_id" UUID,
    "product_id" UUID NOT NULL,
    "viewed_at" TIMESTAMPTZ(6) NOT NULL,
    "view_duration_ms" INTEGER,
    "source" "product_view_source" NOT NULL,

    CONSTRAINT "product_view_pkey" PRIMARY KEY ("id","viewed_at")
) PARTITION BY RANGE ("viewed_at");

CREATE TABLE "product_view_2026_08" PARTITION OF "product_view"
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE "product_view_2026_09" PARTITION OF "product_view"
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE "product_view_2026_10" PARTITION OF "product_view"
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE "product_view_default" PARTITION OF "product_view" DEFAULT;

-- CreateTable
CREATE TABLE "project" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "visitor_id" UUID NOT NULL,
    "app_user_id" UUID,
    "name" TEXT NOT NULL,
    "slug" CITEXT NOT NULL,
    "client_name" TEXT,
    "project_type" "project_type",
    "location_city" TEXT,
    "status" "project_status" NOT NULL DEFAULT 'draft',
    "cover_media_id" UUID,
    "palette" JSONB,
    "total_area_m2" DECIMAL(12,4),
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "archived_at" TIMESTAMPTZ(6),

    CONSTRAINT "project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_zone" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "space_type" "space_type",
    "area_m2" DECIMAL(12,4) NOT NULL,
    "layout_pattern_id" UUID,
    "wastage_pct" DECIMAL(5,2) NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "project_zone_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_item" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "project_id" UUID NOT NULL,
    "zone_id" UUID,
    "product_id" UUID NOT NULL,
    "quantity_m2" DECIMAL(12,4) NOT NULL,
    "role" "project_item_role" NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "note" TEXT,
    "is_selected" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "project_item_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_share" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "project_id" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "permission" "project_share_permission" NOT NULL DEFAULT 'view',
    "expires_at" TIMESTAMPTZ(6),
    "password_hash" TEXT,
    "view_count" INTEGER NOT NULL DEFAULT 0,
    "last_viewed_at" TIMESTAMPTZ(6),
    "revoked_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "project_share_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_comment" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "project_id" UUID NOT NULL,
    "project_item_id" UUID,
    "share_id" UUID,
    "author_name" TEXT NOT NULL,
    "app_user_id" UUID,
    "body" TEXT NOT NULL,
    "is_resolved" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "project_comment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "stock_alert" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "visitor_id" UUID NOT NULL,
    "app_user_id" UUID,
    "product_id" UUID NOT NULL,
    "location_id" UUID,
    "contact_email" TEXT,
    "contact_phone" TEXT,
    "channel" "stock_alert_channel" NOT NULL,
    "min_quantity_m2" DECIMAL(12,4) NOT NULL,
    "status" "stock_alert_status" NOT NULL DEFAULT 'active',
    "notified_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "stock_alert_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "saved_item_tenant_id_visitor_id_idx" ON "saved_item"("tenant_id", "visitor_id");

-- CreateIndex
CREATE UNIQUE INDEX "saved_item_visitor_id_product_id_key" ON "saved_item"("visitor_id", "product_id");

-- CreateIndex
CREATE INDEX "product_view_tenant_id_visitor_id_viewed_at_idx" ON "product_view"("tenant_id", "visitor_id", "viewed_at");

-- CreateIndex
CREATE INDEX "product_view_tenant_id_product_id_viewed_at_idx" ON "product_view"("tenant_id", "product_id", "viewed_at");

-- CreateIndex
CREATE INDEX "project_tenant_id_visitor_id_idx" ON "project"("tenant_id", "visitor_id");

-- CreateIndex
CREATE UNIQUE INDEX "project_tenant_id_slug_key" ON "project"("tenant_id", "slug");

-- CreateIndex
CREATE INDEX "project_zone_project_id_idx" ON "project_zone"("project_id");

-- CreateIndex
CREATE INDEX "project_item_project_id_idx" ON "project_item"("project_id");

-- CreateIndex
CREATE INDEX "project_item_zone_id_idx" ON "project_item"("zone_id");

-- CreateIndex
CREATE UNIQUE INDEX "project_share_token_key" ON "project_share"("token");

-- CreateIndex
CREATE INDEX "project_share_project_id_idx" ON "project_share"("project_id");

-- CreateIndex
CREATE INDEX "project_comment_project_id_idx" ON "project_comment"("project_id");

-- CreateIndex
CREATE INDEX "stock_alert_tenant_id_product_id_status_idx" ON "stock_alert"("tenant_id", "product_id", "status");

-- CreateIndex
CREATE INDEX "stock_alert_tenant_id_visitor_id_idx" ON "stock_alert"("tenant_id", "visitor_id");

-- AddForeignKey — the FK deferred from the commerce domain migration, now
-- that project exists.
ALTER TABLE "showroom_booking" ADD CONSTRAINT "showroom_booking_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item" ADD CONSTRAINT "saved_item_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item" ADD CONSTRAINT "saved_item_visitor_id_fkey" FOREIGN KEY ("visitor_id") REFERENCES "visitor"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item" ADD CONSTRAINT "saved_item_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item" ADD CONSTRAINT "saved_item_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item" ADD CONSTRAINT "saved_item_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_view" ADD CONSTRAINT "product_view_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_view" ADD CONSTRAINT "product_view_visitor_id_fkey" FOREIGN KEY ("visitor_id") REFERENCES "visitor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_view" ADD CONSTRAINT "product_view_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_view" ADD CONSTRAINT "product_view_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project" ADD CONSTRAINT "project_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project" ADD CONSTRAINT "project_visitor_id_fkey" FOREIGN KEY ("visitor_id") REFERENCES "visitor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project" ADD CONSTRAINT "project_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_zone" ADD CONSTRAINT "project_zone_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_zone" ADD CONSTRAINT "project_zone_layout_pattern_id_fkey" FOREIGN KEY ("layout_pattern_id") REFERENCES "layout_pattern"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_item" ADD CONSTRAINT "project_item_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_item" ADD CONSTRAINT "project_item_zone_id_fkey" FOREIGN KEY ("zone_id") REFERENCES "project_zone"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_item" ADD CONSTRAINT "project_item_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_share" ADD CONSTRAINT "project_share_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_comment" ADD CONSTRAINT "project_comment_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_comment" ADD CONSTRAINT "project_comment_project_item_id_fkey" FOREIGN KEY ("project_item_id") REFERENCES "project_item"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_comment" ADD CONSTRAINT "project_comment_share_id_fkey" FOREIGN KEY ("share_id") REFERENCES "project_share"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_comment" ADD CONSTRAINT "project_comment_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_alert" ADD CONSTRAINT "stock_alert_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_alert" ADD CONSTRAINT "stock_alert_visitor_id_fkey" FOREIGN KEY ("visitor_id") REFERENCES "visitor"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_alert" ADD CONSTRAINT "stock_alert_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_alert" ADD CONSTRAINT "stock_alert_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_alert" ADD CONSTRAINT "stock_alert_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE SET NULL ON UPDATE CASCADE;
