-- =============================================================================
-- 0002 · Identity tables — tenant, app_user, visitor
-- docs/03-database-design.md §2.1 – §2.3
--
-- Generated by `prisma migrate diff`, with the CREATE SCHEMA and CREATE
-- EXTENSION statements removed: those belong to migration 0001, which must run
-- first because uuid_generate_v7() is a column default here.
-- =============================================================================

-- CreateEnum
CREATE TYPE "tenant_status" AS ENUM ('active', 'suspended');

-- CreateEnum
CREATE TYPE "measurement_system" AS ENUM ('metric', 'imperial');

-- CreateEnum
CREATE TYPE "measurement_preference" AS ENUM ('m2', 'ft2');

-- CreateEnum
CREATE TYPE "user_type" AS ENUM ('customer', 'designer', 'contractor', 'staff');

-- CreateEnum
CREATE TYPE "app_user_status" AS ENUM ('active', 'invited', 'suspended');

-- CreateTable
CREATE TABLE "tenant" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "slug" CITEXT NOT NULL,
    "name" TEXT NOT NULL,
    "legal_name" TEXT,
    "default_locale" TEXT NOT NULL DEFAULT 'en',
    "supported_locales" TEXT[] DEFAULT ARRAY['en', 'ar']::TEXT[],
    "default_currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "measurement_system" "measurement_system" NOT NULL DEFAULT 'metric',
    "default_wastage_pct" DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "status" "tenant_status" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tenant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_user" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "auth_user_id" UUID,
    "email" CITEXT NOT NULL,
    "phone" TEXT,
    "full_name" TEXT,
    "preferred_locale" TEXT,
    "preferred_currency" CHAR(3),
    "measurement_preference" "measurement_preference",
    "user_type" "user_type" NOT NULL,
    "marketing_opt_in" BOOLEAN NOT NULL DEFAULT false,
    "last_seen_at" TIMESTAMPTZ(6),
    "status" "app_user_status" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "app_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "visitor" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "app_user_id" UUID,
    "first_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "first_referrer" TEXT,
    "first_utm" JSONB,
    "locale" TEXT,
    "country_code" CHAR(2),
    "merged_into_visitor_id" UUID,

    CONSTRAINT "visitor_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenant_slug_key" ON "tenant"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "app_user_auth_user_id_key" ON "app_user"("auth_user_id");

-- CreateIndex
CREATE INDEX "app_user_tenant_id_email_idx" ON "app_user"("tenant_id", "email");

-- CreateIndex
CREATE INDEX "app_user_tenant_id_user_type_status_idx" ON "app_user"("tenant_id", "user_type", "status");

-- CreateIndex
CREATE INDEX "visitor_tenant_id_last_seen_at_idx" ON "visitor"("tenant_id", "last_seen_at");

-- CreateIndex
CREATE INDEX "visitor_tenant_id_app_user_id_idx" ON "visitor"("tenant_id", "app_user_id");

-- AddForeignKey
ALTER TABLE "app_user" ADD CONSTRAINT "app_user_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "visitor" ADD CONSTRAINT "visitor_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "visitor" ADD CONSTRAINT "visitor_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "visitor" ADD CONSTRAINT "visitor_merged_into_visitor_id_fkey" FOREIGN KEY ("merged_into_visitor_id") REFERENCES "visitor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

