-- =============================================================================
-- 0009 · Catalog domain tables
-- docs/03-database-design.md §3
--
-- Generated by `prisma migrate diff`, with the trailing RenameIndex artifact
-- excluded (same reasoning as migration 20260803091500: Phase 0's manual SQL
-- rename of app_user_tenant_id_email_all_idx is correct as it stands).
--
-- Includes the trade_account -> price_tier foreign key deferred from
-- migration 20260803091500, now that price_tier exists to reference.
-- =============================================================================

-- CreateEnum
CREATE TYPE "shade_variation" AS ENUM ('V1', 'V2', 'V3', 'V4');

-- CreateEnum
CREATE TYPE "slip_rating" AS ENUM ('R9', 'R10', 'R11', 'R12', 'R13');

-- CreateEnum
CREATE TYPE "price_visibility" AS ENUM ('public', 'trade_only', 'on_request');

-- CreateEnum
CREATE TYPE "product_status" AS ENUM ('draft', 'review', 'published', 'archived', 'discontinued');

-- CreateEnum
CREATE TYPE "product_source" AS ENUM ('manual', 'ingestion', 'import', 'api');

-- CreateEnum
CREATE TYPE "attribute_data_type" AS ENUM ('text', 'number', 'boolean', 'enum');

-- CreateEnum
CREATE TYPE "product_relation_type" AS ENUM ('related', 'trim', 'complete_the_look', 'same_look_different_format', 'same_look_lower_price', 'replacement', 'variant');

-- CreateTable
CREATE TABLE "brand" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "slug" CITEXT NOT NULL,
    "name" TEXT NOT NULL,
    "logo_media_id" UUID,
    "origin_country" CHAR(2),
    "website_url" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "brand_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "collection" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "brand_id" UUID,
    "slug" CITEXT NOT NULL,
    "hero_media_id" UUID,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "status" "product_status" NOT NULL DEFAULT 'draft',
    "published_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "collection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "collection_translation" (
    "collection_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "seo_title" TEXT,
    "seo_description" TEXT,

    CONSTRAINT "collection_translation_pkey" PRIMARY KEY ("collection_id","locale")
);

-- CreateTable
CREATE TABLE "category" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "parent_id" UUID,
    "slug" CITEXT NOT NULL,
    "path" ltree,
    "depth" INTEGER NOT NULL DEFAULT 0,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "material" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "material_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "material_translation" (
    "material_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "material_translation_pkey" PRIMARY KEY ("material_id","locale")
);

-- CreateTable
CREATE TABLE "finish" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "finish_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "finish_translation" (
    "finish_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "finish_translation_pkey" PRIMARY KEY ("finish_id","locale")
);

-- CreateTable
CREATE TABLE "surface_look" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "surface_look_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "surface_look_translation" (
    "surface_look_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "surface_look_translation_pkey" PRIMARY KEY ("surface_look_id","locale")
);

-- CreateTable
CREATE TABLE "color_family" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "color_hex" CHAR(7),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "color_family_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "color_family_translation" (
    "color_family_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "color_family_translation_pkey" PRIMARY KEY ("color_family_id","locale")
);

-- CreateTable
CREATE TABLE "application" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "application_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "application_translation" (
    "application_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "application_translation_pkey" PRIMARY KEY ("application_id","locale")
);

-- CreateTable
CREATE TABLE "layout_pattern" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "default_wastage_pct" DECIMAL(5,2) NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "icon" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "layout_pattern_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "layout_pattern_translation" (
    "layout_pattern_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "layout_pattern_translation_pkey" PRIMARY KEY ("layout_pattern_id","locale")
);

-- CreateTable
CREATE TABLE "product" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "sku" CITEXT NOT NULL,
    "supplier_sku" TEXT,
    "ean" TEXT,
    "gtin" TEXT,
    "brand_id" UUID NOT NULL,
    "collection_id" UUID,
    "category_id" UUID NOT NULL,
    "width_mm" INTEGER NOT NULL,
    "height_mm" INTEGER NOT NULL,
    "thickness_mm" DECIMAL(5,2) NOT NULL,
    "nominal_format" TEXT,
    "format_group" TEXT,
    "material_id" UUID NOT NULL,
    "finish_id" UUID NOT NULL,
    "surface_look_id" UUID NOT NULL,
    "color_family_id" UUID NOT NULL,
    "color_hex" CHAR(7),
    "color_lab" numeric(6,3)[],
    "is_rectified" BOOLEAN NOT NULL DEFAULT false,
    "shade_variation" "shade_variation",
    "slip_rating" "slip_rating",
    "pei_class" INTEGER,
    "water_absorption_pct" DECIMAL(5,3),
    "is_frost_resistant" BOOLEAN,
    "is_indoor" BOOLEAN NOT NULL,
    "is_outdoor" BOOLEAN NOT NULL,
    "application_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "pieces_per_box" INTEGER NOT NULL,
    "m2_per_box" DECIMAL(8,4) NOT NULL,
    "kg_per_box" DECIMAL(8,3) NOT NULL,
    "boxes_per_pallet" INTEGER,
    "origin_country" CHAR(2),
    "base_price" DECIMAL(12,4),
    "currency" CHAR(3) NOT NULL,
    "price_visibility" "price_visibility" NOT NULL,
    "status" "product_status" NOT NULL DEFAULT 'draft',
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "is_new" BOOLEAN NOT NULL DEFAULT false,
    "published_at" TIMESTAMPTZ(6),
    "discontinued_at" TIMESTAMPTZ(6),
    "primary_media_id" UUID,
    "search_boost" DECIMAL(4,2) NOT NULL DEFAULT 1.0,
    "created_by" UUID,
    "updated_by" UUID,
    "source" "product_source" NOT NULL DEFAULT 'manual',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_translation" (
    "product_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" CITEXT NOT NULL,
    "short_description" TEXT,
    "description" TEXT,
    "installation_notes" TEXT,
    "care_instructions" TEXT,
    "seo_title" TEXT,
    "seo_description" TEXT,
    "og_title" TEXT,
    "og_description" TEXT,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "search_vector" tsvector,
    "is_machine_translated" BOOLEAN NOT NULL DEFAULT false,
    "reviewed_by" UUID,
    "reviewed_at" TIMESTAMPTZ(6),

    CONSTRAINT "product_translation_pkey" PRIMARY KEY ("product_id","locale")
);

-- CreateTable
CREATE TABLE "product_attribute" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "data_type" "attribute_data_type" NOT NULL,
    "unit" TEXT,
    "is_filterable" BOOLEAN NOT NULL DEFAULT false,
    "is_comparable" BOOLEAN NOT NULL DEFAULT false,
    "display_group" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "product_attribute_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_attribute_translation" (
    "attribute_id" UUID NOT NULL,
    "locale" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "product_attribute_translation_pkey" PRIMARY KEY ("attribute_id","locale")
);

-- CreateTable
CREATE TABLE "product_attribute_value" (
    "product_id" UUID NOT NULL,
    "attribute_id" UUID NOT NULL,
    "value_text" TEXT,
    "value_number" DECIMAL(14,4),
    "value_boolean" BOOLEAN,
    "value_option_id" UUID,

    CONSTRAINT "product_attribute_value_pkey" PRIMARY KEY ("product_id","attribute_id")
);

-- CreateTable
CREATE TABLE "product_relation" (
    "product_id" UUID NOT NULL,
    "related_product_id" UUID NOT NULL,
    "relation_type" "product_relation_type" NOT NULL,
    "rank" INTEGER NOT NULL DEFAULT 0,
    "is_automatic" BOOLEAN NOT NULL DEFAULT false,
    "confidence" DECIMAL(4,3),

    CONSTRAINT "product_relation_pkey" PRIMARY KEY ("product_id","related_product_id","relation_type")
);

-- CreateTable
CREATE TABLE "price_tier" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "discount_pct" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "min_annual_volume" DECIMAL(12,4),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_default" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "price_tier_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_price" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "price_tier_id" UUID NOT NULL,
    "price" DECIMAL(12,4) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "min_quantity_m2" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "valid_from" TIMESTAMPTZ(6) NOT NULL,
    "valid_to" TIMESTAMPTZ(6),
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_price_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "brand_tenant_id_slug_idx" ON "brand"("tenant_id", "slug");

-- CreateIndex
CREATE INDEX "collection_tenant_id_slug_idx" ON "collection"("tenant_id", "slug");

-- CreateIndex
CREATE INDEX "collection_tenant_id_brand_id_idx" ON "collection"("tenant_id", "brand_id");

-- CreateIndex
CREATE INDEX "category_tenant_id_parent_id_idx" ON "category"("tenant_id", "parent_id");

-- CreateIndex
CREATE UNIQUE INDEX "material_tenant_id_key_key" ON "material"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "finish_tenant_id_key_key" ON "finish"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "surface_look_tenant_id_key_key" ON "surface_look"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "color_family_tenant_id_key_key" ON "color_family"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "application_tenant_id_key_key" ON "application"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "layout_pattern_tenant_id_key_key" ON "layout_pattern"("tenant_id", "key");

-- CreateIndex
CREATE INDEX "product_tenant_id_brand_id_idx" ON "product"("tenant_id", "brand_id");

-- CreateIndex
CREATE INDEX "product_tenant_id_category_id_idx" ON "product"("tenant_id", "category_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_attribute_tenant_id_key_key" ON "product_attribute"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "price_tier_tenant_id_key_key" ON "price_tier"("tenant_id", "key");

-- CreateIndex
CREATE UNIQUE INDEX "product_price_product_id_price_tier_id_min_quantity_m2_vali_key" ON "product_price"("product_id", "price_tier_id", "min_quantity_m2", "valid_from");

-- AddForeignKey
ALTER TABLE "brand" ADD CONSTRAINT "brand_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "collection" ADD CONSTRAINT "collection_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "collection" ADD CONSTRAINT "collection_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "brand"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "collection_translation" ADD CONSTRAINT "collection_translation_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category" ADD CONSTRAINT "category_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category" ADD CONSTRAINT "category_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material" ADD CONSTRAINT "material_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material_translation" ADD CONSTRAINT "material_translation_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "material"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "finish" ADD CONSTRAINT "finish_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "finish_translation" ADD CONSTRAINT "finish_translation_finish_id_fkey" FOREIGN KEY ("finish_id") REFERENCES "finish"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "surface_look" ADD CONSTRAINT "surface_look_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "surface_look_translation" ADD CONSTRAINT "surface_look_translation_surface_look_id_fkey" FOREIGN KEY ("surface_look_id") REFERENCES "surface_look"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "color_family" ADD CONSTRAINT "color_family_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "color_family_translation" ADD CONSTRAINT "color_family_translation_color_family_id_fkey" FOREIGN KEY ("color_family_id") REFERENCES "color_family"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "application" ADD CONSTRAINT "application_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "application_translation" ADD CONSTRAINT "application_translation_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "application"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "layout_pattern" ADD CONSTRAINT "layout_pattern_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "layout_pattern_translation" ADD CONSTRAINT "layout_pattern_translation_layout_pattern_id_fkey" FOREIGN KEY ("layout_pattern_id") REFERENCES "layout_pattern"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "brand"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "material"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_finish_id_fkey" FOREIGN KEY ("finish_id") REFERENCES "finish"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_surface_look_id_fkey" FOREIGN KEY ("surface_look_id") REFERENCES "surface_look"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_color_family_id_fkey" FOREIGN KEY ("color_family_id") REFERENCES "color_family"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_translation" ADD CONSTRAINT "product_translation_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute" ADD CONSTRAINT "product_attribute_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute_translation" ADD CONSTRAINT "product_attribute_translation_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "product_attribute"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute_value" ADD CONSTRAINT "product_attribute_value_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute_value" ADD CONSTRAINT "product_attribute_value_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "product_attribute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_relation" ADD CONSTRAINT "product_relation_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_relation" ADD CONSTRAINT "product_relation_related_product_id_fkey" FOREIGN KEY ("related_product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "price_tier" ADD CONSTRAINT "price_tier_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_price" ADD CONSTRAINT "product_price_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_price" ADD CONSTRAINT "product_price_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_price" ADD CONSTRAINT "product_price_price_tier_id_fkey" FOREIGN KEY ("price_tier_id") REFERENCES "price_tier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_account" ADD CONSTRAINT "trade_account_price_tier_id_fkey" FOREIGN KEY ("price_tier_id") REFERENCES "price_tier"("id") ON DELETE SET NULL ON UPDATE CASCADE;


