-- =============================================================================
-- 0025 · Analytics domain — tables
-- docs/03-database-design.md §10, §13.2
-- =============================================================================
--
-- Prisma-generated DDL, usual diff noise excluded. analytics_event is built
-- directly as a monthly RANGE-partitioned table (by occurred_at, §13.2),
-- same as product_view/ai_interaction.

-- CreateEnum
CREATE TYPE "analytics_event_type" AS ENUM ('product_view', 'product_click', 'filter_apply', 'filter_clear', 'search', 'search_no_results', 'sort_change', 'finder_upload', 'finder_result_view', 'finder_result_click', 'assistant_session_start', 'assistant_message', 'assistant_recommendation_click', 'wishlist_add', 'wishlist_remove', 'basket_add', 'basket_remove', 'zone_add', 'zone_remove', 'quote_submit', 'quote_view', 'sample_request', 'sample_ship', 'booking_request', 'booking_confirm', 'project_create', 'project_item_add', 'share_project', 'project_comment', 'stock_alert_create', 'stock_alert_notify', 'showroom_locator_view', 'page_view', 'locale_switch', 'currency_switch', 'trade_account_apply', 'auth_signup', 'auth_login');

-- CreateEnum
CREATE TYPE "analytics_entity_type" AS ENUM ('product', 'category', 'brand', 'collection', 'quote_request', 'sample_request', 'project', 'ai_conversation', 'finder_session', 'showroom_booking');

-- CreateTable (partitioned — see file header)
CREATE TABLE "analytics_event" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" UUID NOT NULL,
    "visitor_id" UUID,
    "app_user_id" UUID,
    "session_id" UUID,
    "event_type" "analytics_event_type" NOT NULL,
    "entity_type" "analytics_entity_type",
    "entity_id" UUID,
    "properties" JSONB,
    "locale" TEXT,
    "country_code" CHAR(2),
    "device_type" TEXT,
    "referrer_domain" TEXT,
    "utm" JSONB,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "analytics_event_pkey" PRIMARY KEY ("id","occurred_at")
) PARTITION BY RANGE ("occurred_at");

CREATE TABLE "analytics_event_2026_08" PARTITION OF "analytics_event"
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE "analytics_event_2026_09" PARTITION OF "analytics_event"
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE "analytics_event_2026_10" PARTITION OF "analytics_event"
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE "analytics_event_default" PARTITION OF "analytics_event" DEFAULT;

-- CreateTable
CREATE TABLE "daily_product_stat" (
    "tenant_id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "views" INTEGER NOT NULL DEFAULT 0,
    "unique_visitors" INTEGER NOT NULL DEFAULT 0,
    "basket_adds" INTEGER NOT NULL DEFAULT 0,
    "quote_inclusions" INTEGER NOT NULL DEFAULT 0,
    "finder_appearances" INTEGER NOT NULL DEFAULT 0,
    "finder_clicks" INTEGER NOT NULL DEFAULT 0,
    "saves" INTEGER NOT NULL DEFAULT 0,
    "conversion_rate" DECIMAL(6,5),

    CONSTRAINT "daily_product_stat_pkey" PRIMARY KEY ("tenant_id","product_id","date")
);

-- CreateTable
CREATE TABLE "daily_search_stat" (
    "tenant_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "normalized_query" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "result_count" INTEGER NOT NULL DEFAULT 0,
    "click_through" INTEGER NOT NULL DEFAULT 0,
    "is_zero_result" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "daily_search_stat_pkey" PRIMARY KEY ("tenant_id","date","normalized_query")
);

-- CreateTable
CREATE TABLE "daily_filter_stat" (
    "tenant_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "filter_signature" TEXT NOT NULL,
    "applications" INTEGER NOT NULL DEFAULT 0,
    "result_counts" INTEGER NOT NULL DEFAULT 0,
    "zero_result_count" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "daily_filter_stat_pkey" PRIMARY KEY ("tenant_id","date","filter_signature")
);

-- CreateTable
CREATE TABLE "daily_ai_stat" (
    "tenant_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "feature" "ai_feature" NOT NULL,
    "calls" INTEGER NOT NULL DEFAULT 0,
    "cost_usd" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "mean_latency_ms" INTEGER,
    "error_rate" DECIMAL(5,4),
    "cache_hit_rate" DECIMAL(5,4),
    "mean_confidence" DECIMAL(4,3),
    "positive_feedback_rate" DECIMAL(5,4),

    CONSTRAINT "daily_ai_stat_pkey" PRIMARY KEY ("tenant_id","date","feature")
);

-- CreateTable
CREATE TABLE "daily_quote_stat" (
    "tenant_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "source" "quote_source" NOT NULL,
    "submitted" INTEGER NOT NULL DEFAULT 0,
    "value" DECIMAL(14,4) NOT NULL DEFAULT 0,
    "won" INTEGER NOT NULL DEFAULT 0,
    "lost" INTEGER NOT NULL DEFAULT 0,
    "mean_response_hours" DECIMAL(8,2),

    CONSTRAINT "daily_quote_stat_pkey" PRIMARY KEY ("tenant_id","date","source")
);

-- CreateIndex
CREATE INDEX "analytics_event_tenant_id_event_type_occurred_at_idx" ON "analytics_event"("tenant_id", "event_type", "occurred_at");

-- CreateIndex
CREATE INDEX "analytics_event_tenant_id_visitor_id_occurred_at_idx" ON "analytics_event"("tenant_id", "visitor_id", "occurred_at");

-- CreateIndex
CREATE INDEX "analytics_event_tenant_id_entity_type_entity_id_occurred_at_idx" ON "analytics_event"("tenant_id", "entity_type", "entity_id", "occurred_at");

-- AddForeignKey
ALTER TABLE "analytics_event" ADD CONSTRAINT "analytics_event_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "analytics_event" ADD CONSTRAINT "analytics_event_visitor_id_fkey" FOREIGN KEY ("visitor_id") REFERENCES "visitor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "analytics_event" ADD CONSTRAINT "analytics_event_app_user_id_fkey" FOREIGN KEY ("app_user_id") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_product_stat" ADD CONSTRAINT "daily_product_stat_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_product_stat" ADD CONSTRAINT "daily_product_stat_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_search_stat" ADD CONSTRAINT "daily_search_stat_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_filter_stat" ADD CONSTRAINT "daily_filter_stat_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_ai_stat" ADD CONSTRAINT "daily_ai_stat_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "daily_quote_stat" ADD CONSTRAINT "daily_quote_stat_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
